In [2]:
 import pandas as pd

In [3]:
# DataSets Loading
climate_raw = pd.read_csv("../data/raw/climate_data_nepal_district_wise_monthly_province_grouped.csv")
glacier_raw = pd.read_csv("../data/raw/nepal_glacier_data.csv")

In [4]:
climate_raw.head()

,date,year,month,district,province,latitude,longitude,precipitation_total,surface_pressure,specific_humidity_2m,...,surface_skin_temp,wind_speed_10m,max_wind_speed_10m,min_wind_speed_10m,wind_speed_range_10m,wind_speed_50m,max_wind_speed_50m,min_wind_speed_50m,wind_speed_range_50m,province.1
0,1981-01-31,1981,1,Arghakhanchi,5,27.9,83.2,67.31,93.78,5.28,...,11.19,2.01,3.39,0.81,2.59,2.70,4.22,1.06,3.16,5.0
1,1981-02-28,1981,2,Arghakhanchi,5,27.9,83.2,3.37,93.52,5.13,...,15.10,2.58,4.88,0.95,3.94,3.51,5.62,1.09,4.53,5.0
2,1981-03-31,1981,3,Arghakhanchi,5,27.9,83.2,26.02,93.40,5.91,...,20.58,2.73,4.67,1.02,3.65,3.73,5.72,1.38,4.34,5.0
3,1981-04-30,1981,4,Arghakhanchi,5,27.9,83.2,46.15,93.03,6.52,...,25.63,2.89,4.78,1.07,3.72,3.82,5.66,1.35,4.31,5.0
4,1981-05-31,1981,5,Arghakhanchi,5,27.9,83.2,69.45,92.75,9.95,...,29.99,2.69,4.40,0.93,3.47,3.52,5.29,1.30,4.00,5.0

In [5]:
print(climate_raw.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29016 entries, 0 to 29015
Data columns (total 26 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   date                  29016 non-null  object
 1   year                  29016 non-null  int64
 2   month                 29016 non-null  int64
 3   district              29016 non-null  object
 4   province              29016 non-null  int64
 5   latitude              29016 non-null  float64
 6   longitude             29016 non-null  float64
 7   precipitation_total   29016 non-null  float64
 8   surface_pressure      29016 non-null  float64
 9   specific_humidity_2m  29016 non-null  float64
 10  relative_humidity_2m  29016 non-null  float64
 11  air_temp_2m           29016 non-null  float64
 12  wet_bulb_temp_2m      29016 non-null  float64
 13  max_temp_2m           29016 non-null  float64
 14  min_temp_2m           29016 non-null  float64
 15  temp_range_2m         29016 non-null  float64
 16  surface_skin_temp     29016 non-null  float64
 17  wind_speed_10m        29016 non-null  float64
 18  max_wind_speed_10m    29016 non-null  float64
 19  min_wind_speed_10m    29016 non-null  float64
 20  wind_speed_range_10m  29016 non-null  float64
 21  wind_speed_50m        29016 non-null  float64
 22  max_wind_speed_50m    29016 non-null  float64
 23  min_wind_speed_50m    29016 non-null  float64
 24  wind_speed_range_50m  29016 non-null  float64
 25  province.1            24804 non-null  float64
dtypes: float64(21), int64(3), object(2)
memory usage: 5.8+ MB
None

In [6]:
climate_raw.describe()

,year,month,province,latitude,longitude,precipitation_total,surface_pressure,specific_humidity_2m,relative_humidity_2m,air_temp_2m,...,surface_skin_temp,wind_speed_10m,max_wind_speed_10m,min_wind_speed_10m,wind_speed_range_10m,wind_speed_50m,max_wind_speed_50m,min_wind_speed_50m,wind_speed_range_50m,province.1
count,29016.000000,29016.000000,29016.000000,29016.000000,29016.000000,29016.000000,29016.000000,29016.000000,29016.000000,29016.000000,...,29016.000000,29016.000000,29016.000000,29016.000000,29016.000000,29016.000000,29016.000000,29016.000000,29016.000000,24804.000000
mean,2000.000000,6.500000,3.758065,27.970645,84.273226,68.922705,82.903742,8.465428,55.560993,15.795138,...,15.515834,2.373433,4.675816,0.667401,4.008437,2.732222,4.646797,0.924362,3.722418,3.811321
std,11.254823,3.452112,1.964931,0.880253,2.198102,98.874269,10.713284,5.217317,20.731268,9.044101,...,9.774112,0.493615,1.014603,0.321686,1.009005,0.742617,1.068191,0.515904,0.867557,1.991120
min,1981.000000,1.000000,1.000000,26.500000,80.200000,0.000000,55.460000,0.750000,8.510000,-17.810000,...,-22.780000,1.380000,2.220000,0.180000,1.630000,1.430000,2.580000,0.200000,1.750000,1.000000
25%,1990.000000,3.750000,2.000000,27.300000,82.350000,3.740000,77.700000,4.080000,38.800000,10.027500,...,9.240000,1.980000,3.950000,0.430000,3.270000,2.210000,3.860000,0.550000,3.070000,2.000000
50%,2000.000000,6.500000,4.000000,27.950000,84.300000,22.050000,83.725000,6.730000,52.670000,16.660000,...,16.400000,2.330000,4.580000,0.590000,3.920000,2.590000,4.500000,0.780000,3.560000,4.000000
75%,2010.000000,9.250000,5.000000,28.600000,85.900000,99.745000,92.790000,12.870000,74.830000,22.390000,...,22.640000,2.690000,5.310000,0.830000,4.680000,3.130000,5.240000,1.150000,4.260000,5.000000
max,2019.000000,12.000000,7.000000,30.000000,88.000000,641.840000,99.780000,21.700000,94.820000,35.590000,...,38.110000,5.840000,10.850000,3.100000,8.480000,7.430000,11.890000,4.460000,8.410000,7.000000

In [7]:
climate_raw.isnull().sum()

date                       0
year                       0
month                      0
district                   0
province                   0
latitude                   0
longitude                  0
precipitation_total        0
surface_pressure           0
specific_humidity_2m       0
relative_humidity_2m       0
air_temp_2m                0
wet_bulb_temp_2m           0
max_temp_2m                0
min_temp_2m                0
temp_range_2m              0
surface_skin_temp          0
wind_speed_10m             0
max_wind_speed_10m         0
min_wind_speed_10m         0
wind_speed_range_10m       0
wind_speed_50m             0
max_wind_speed_50m         0
min_wind_speed_50m         0
wind_speed_range_50m       0
province.1              4212
dtype: int64

In [8]:
# fill the null province values with forward fill
climate_raw['province.1'] = climate_raw['province.1'].ffill()

In [9]:
climate_raw.head()

,date,year,month,district,province,latitude,longitude,precipitation_total,surface_pressure,specific_humidity_2m,...,surface_skin_temp,wind_speed_10m,max_wind_speed_10m,min_wind_speed_10m,wind_speed_range_10m,wind_speed_50m,max_wind_speed_50m,min_wind_speed_50m,wind_speed_range_50m,province.1
0,1981-01-31,1981,1,Arghakhanchi,5,27.9,83.2,67.31,93.78,5.28,...,11.19,2.01,3.39,0.81,2.59,2.70,4.22,1.06,3.16,5.0
1,1981-02-28,1981,2,Arghakhanchi,5,27.9,83.2,3.37,93.52,5.13,...,15.10,2.58,4.88,0.95,3.94,3.51,5.62,1.09,4.53,5.0
2,1981-03-31,1981,3,Arghakhanchi,5,27.9,83.2,26.02,93.40,5.91,...,20.58,2.73,4.67,1.02,3.65,3.73,5.72,1.38,4.34,5.0
3,1981-04-30,1981,4,Arghakhanchi,5,27.9,83.2,46.15,93.03,6.52,...,25.63,2.89,4.78,1.07,3.72,3.82,5.66,1.35,4.31,5.0
4,1981-05-31,1981,5,Arghakhanchi,5,27.9,83.2,69.45,92.75,9.95,...,29.99,2.69,4.40,0.93,3.47,3.52,5.29,1.30,4.00,5.0

In [10]:
climate_raw['date'] = pd.to_datetime(climate_raw['date'], format = 'mixed', dayfirst = 'false')

In [11]:
print(climate_raw['date'].dtype)
print(climate_raw['year'].dtype)
print(climate_raw['year'].dtype)

datetime64[ns]
int64
int64

In [12]:
# drop province.1
climate_raw = climate_raw.drop('province.1', axis = 1)

In [13]:
# drop a duplicate value
climate_raw.drop_duplicates(inplace=True)

In [14]:
glacier_raw.head()

,Glacier ID,Political Unit,Continent,Basin Code,Location Code,Glacier Code,Latitude,Longitude,Primary Class,Glacier Source,...,Mean Length,Mean Depth,Accumulation Orientation,Ablation Orientation,Topographic Map Year,Topographic Map Scale,Photograph Year,Height Range,Average Slope (deg),Compactness
0,NP5O163G0001,NEPAL,ASIA,O163,G0,1,30.173,80.929,6.0,1.0,...,1.52,36.90,NW,NW,1966,63360.0,1992,613.5,21.979911,0.157895
1,NP5O163G0002,NEPAL,ASIA,O163,G0,2,30.184,80.944,6.0,1.0,...,2.53,48.04,NE,NE,1979,63360.0,1993,613.5,13.630560,0.189723
2,NP5O163G0003,NEPAL,ASIA,O163,G0,3,30.191,80.967,6.0,1.0,...,1.46,35.44,N,N,1974,63360.0,1996,613.5,22.792413,0.148402
3,NP5O163G0004,NEPAL,ASIA,O163,G0,4,30.178,80.979,6.0,1.0,...,2.15,41.57,NW,NW,1970,63360.0,1992,613.5,15.926036,0.151938
4,NP5O163G0005,NEPAL,ASIA,O163,G0,5,30.209,81.032,6.0,1.0,...,0.57,32.91,SW,SW,1967,63360.0,1998,613.5,47.104981,0.315789

In [15]:
climate_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29016 entries, 0 to 29015
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   date                  29016 non-null  datetime64[ns]
 1   year                  29016 non-null  int64
 2   month                 29016 non-null  int64
 3   district              29016 non-null  object
 4   province              29016 non-null  int64
 5   latitude              29016 non-null  float64
 6   longitude             29016 non-null  float64
 7   precipitation_total   29016 non-null  float64
 8   surface_pressure      29016 non-null  float64
 9   specific_humidity_2m  29016 non-null  float64
 10  relative_humidity_2m  29016 non-null  float64
 11  air_temp_2m           29016 non-null  float64
 12  wet_bulb_temp_2m      29016 non-null  float64
 13  max_temp_2m           29016 non-null  float64
 14  min_temp_2m           29016 non-null  float64
 15  temp_range_2m         29016 non-null  float64
 16  surface_skin_temp     29016 non-null  float64
 17  wind_speed_10m        29016 non-null  float64
 18  max_wind_speed_10m    29016 non-null  float64
 19  min_wind_speed_10m    29016 non-null  float64
 20  wind_speed_range_10m  29016 non-null  float64
 21  wind_speed_50m        29016 non-null  float64
 22  max_wind_speed_50m    29016 non-null  float64
 23  min_wind_speed_50m    29016 non-null  float64
 24  wind_speed_range_50m  29016 non-null  float64
dtypes: datetime64[ns](1), float64(20), int64(3), object(1)
memory usage: 5.5+ MB

In [16]:
climate_raw.describe()

,date,year,month,province,latitude,longitude,precipitation_total,surface_pressure,specific_humidity_2m,relative_humidity_2m,...,temp_range_2m,surface_skin_temp,wind_speed_10m,max_wind_speed_10m,min_wind_speed_10m,wind_speed_range_10m,wind_speed_50m,max_wind_speed_50m,min_wind_speed_50m,wind_speed_range_50m
count,29016,29016.000000,29016.000000,29016.000000,29016.000000,29016.000000,29016.000000,29016.000000,29016.000000,29016.000000,...,29016.000000,29016.000000,29016.000000,29016.000000,29016.000000,29016.000000,29016.000000,29016.000000,29016.000000,29016.000000
mean,2000-07-15 12:18:27.692307712,2000.000000,6.500000,3.758065,27.970645,84.273226,68.922705,82.903742,8.465428,55.560993,...,10.810601,15.515834,2.373433,4.675816,0.667401,4.008437,2.732222,4.646797,0.924362,3.722418
min,1981-01-31 00:00:00,1981.000000,1.000000,1.000000,26.500000,80.200000,0.000000,55.460000,0.750000,8.510000,...,4.610000,-22.780000,1.380000,2.220000,0.180000,1.630000,1.430000,2.580000,0.200000,1.750000
25%,1990-10-23 06:00:00,1990.000000,3.750000,2.000000,27.300000,82.350000,3.740000,77.700000,4.080000,38.800000,...,8.560000,9.240000,1.980000,3.950000,0.430000,3.270000,2.210000,3.860000,0.550000,3.070000
50%,2000-07-15 12:00:00,2000.000000,6.500000,4.000000,27.950000,84.300000,22.050000,83.725000,6.730000,52.670000,...,11.170000,16.400000,2.330000,4.580000,0.590000,3.920000,2.590000,4.500000,0.780000,3.560000
75%,2010-04-07 12:00:00,2010.000000,9.250000,5.000000,28.600000,85.900000,99.745000,92.790000,12.870000,74.830000,...,12.910000,22.640000,2.690000,5.310000,0.830000,4.680000,3.130000,5.240000,1.150000,4.260000
max,2019-12-31 00:00:00,2019.000000,12.000000,7.000000,30.000000,88.000000,641.840000,99.780000,21.700000,94.820000,...,18.990000,38.110000,5.840000,10.850000,3.100000,8.480000,7.430000,11.890000,4.460000,8.410000
std,NaN,11.254823,3.452112,1.964931,0.880253,2.198102,98.874269,10.713284,5.217317,20.731268,...,2.812717,9.774112,0.493615,1.014603,0.321686,1.009005,0.742617,1.068191,0.515904,0.867557

In [17]:
climate_raw.isnull().sum()

date                    0
year                    0
month                   0
district                0
province                0
latitude                0
longitude               0
precipitation_total     0
surface_pressure        0
specific_humidity_2m    0
relative_humidity_2m    0
air_temp_2m             0
wet_bulb_temp_2m        0
max_temp_2m             0
min_temp_2m             0
temp_range_2m           0
surface_skin_temp       0
wind_speed_10m          0
max_wind_speed_10m      0
min_wind_speed_10m      0
wind_speed_range_10m    0
wind_speed_50m          0
max_wind_speed_50m      0
min_wind_speed_50m      0
wind_speed_range_50m    0
dtype: int64

In [18]:
glacier_raw.isnull().sum()

Glacier ID                        0
Political Unit                    0
Continent                         0
Basin Code                        0
Location Code                     0
Glacier Code                      0
Latitude                          0
Longitude                         0
Primary Class                     0
Glacier Source                    0
Glacier Form                      0
Minimum Elevation                 0
Minimum Elevation Exposed         0
Mean Elevation                    0
Mean Elevation Accumulation       0
Mean Elevation Ablation           0
Maximum Elevation                 0
Snow Line Elevation            3249
Snow Line Accuracy                0
Glacier Area                      0
Mean Length                       0
Mean Depth                        0
Accumulation Orientation          0
Ablation Orientation              0
Topographic Map Year              0
Topographic Map Scale             0
Photograph Year                   0
Height Range                      0
Average Slope (deg)               0
Compactness                       0
dtype: int64

In [19]:
glacier_raw = glacier_raw.drop(["Minimum Elevation Exposed","Mean Elevation Accumulation","Mean Elevation Ablation","Snow Line Accuracy"], axis = 1)

In [20]:
# delete duplicate values
glacier_raw.drop_duplicates(inplace=True)

In [21]:
# save the processed data 
climate_raw.to_csv('../data/processed/climate_data_cleaned.csv', index=False)
glacier_raw.to_csv('../data/processed/glacier_data_cleaned.csv', index = False)