In [2]:
import pandas as pd
import sys
sys.path.append('../features')  # or 'features' depending on your notebook location

from climate_features import engineer_climate_features
from glacier_features import engineer_glacier_features

In [3]:
# Load cleaned data
climate_df = pd.read_csv("../data/processed/climate_data_cleaned.csv")
glacier_df = pd.read_csv("../data/processed/glacier_data_cleaned.csv")

In [4]:
# Apply feature engineering
climate_feat = engineer_climate_features(climate_df)
glacier_feat = engineer_glacier_features(glacier_df)

In [5]:
# Save to new files
climate_feat.to_csv("../data/featured/feature_climate.csv", index=False)
glacier_feat.to_csv("../data/featured/feature_glacier.csv", index=False)

In [8]:
saved_feature = pd.read_csv("../data/featured/feature_glacier.csv")

In [9]:
saved_feature.head()

,Glacier ID,Political Unit,Continent,Basin Code,Location Code,Glacier Code,Latitude,Longitude,Primary Class,Glacier Source,...,Topographic Map Year,Topographic Map Scale,Photograph Year,Height Range,Average Slope (deg),Compactness,elevation_range,area_per_length,area_per_depth,elevation_to_slope_ratio
0,NP5O163G0001,NEPAL,ASIA,O163,G0,1,30.173,80.929,6.0,1.0,...,1966,63360.0,1992,613.5,21.979911,0.157895,613.5,0.473684,0.019512,248.909111
1,NP5O163G0002,NEPAL,ASIA,O163,G0,2,30.184,80.944,6.0,1.0,...,1979,63360.0,1993,613.5,13.630560,0.189723,613.5,0.569170,0.029975,401.377501
2,NP5O163G0003,NEPAL,ASIA,O163,G0,3,30.191,80.967,6.0,1.0,...,1974,63360.0,1996,613.5,22.792413,0.148402,613.5,0.445205,0.018341,240.036018
3,NP5O163G0004,NEPAL,ASIA,O163,G0,4,30.178,80.979,6.0,1.0,...,1970,63360.0,1992,613.5,15.926036,0.151938,613.5,0.455814,0.023575,343.525540
4,NP5O163G0005,NEPAL,ASIA,O163,G0,5,30.209,81.032,6.0,1.0,...,1967,63360.0,1998,613.5,47.104981,0.315789,613.5,0.947368,0.016408,116.144830

In [10]:
print(saved_feature.columns)

Index(['Glacier ID', 'Political Unit', 'Continent', 'Basin Code',
       'Location Code', 'Glacier Code', 'Latitude', 'Longitude',
       'Primary Class', 'Glacier Source', 'Glacier Form', 'Minimum Elevation',
       'Mean Elevation', 'Maximum Elevation', 'Snow Line Elevation',
       'Glacier Area', 'Mean Length', 'Mean Depth', 'Accumulation Orientation',
       'Ablation Orientation', 'Topographic Map Year', 'Topographic Map Scale',
       'Photograph Year', 'Height Range', 'Average Slope (deg)', 'Compactness',
       'elevation_range', 'area_per_length', 'area_per_depth',
       'elevation_to_slope_ratio'],
      dtype='object')